### ISSUE TITLE
Dependencies cannot be installed

### ISSUE THREAD

**Issue by swails** [erlio/vmq_mzbench#1]
Hi,

In trying to build `vmq_mzbench`, I hit the following snag immediately:

```
jswails@localhost ~/src/verne/vmq_mzbench (master) $ ./rebar compile
==> vmq_mzbench (compile)
Dependency not available: lager-.* ({git,"git://github.com/basho/lager.git",
                                     {tag,"2.2.0"}})
Dependency not available: vmq_commons-.* ({git,
                                           "git://github.com/ioolkos/vmq_commons.git",
                                           {branch,"master"}})
ERROR: compile failed while processing /home/jswails/src/verne/vmq_mzbench: rebar_abort
```

I'm not sure why rebar didn't go out and check out those repos automatically...  Any ideas what I can do?

Thanks!

**Comment by ioolkos** [comment]
`rebar get-deps`
`rebar com`

Thanks for asking & apologies for not documenting that!

**Comment by ioolkos** [comment]
Updated docu on site & added link on readme.

Thanks again, Jason!

**Comment by swails** [comment]
Ah!  Perhaps if I knew erlang and its ecosystem better (i.e., _at all_), I'd have known this :).  What confused me is that the install process for `vernemq` didn't have this step -- `make rel` did this for me, which is why I was expecting (naively, to be sure) the same kind of behavior here and didn't investigate further before asking.

Thank you for the quick response and resolution!
