### ISSUE TITLE
mqtt.message.consumed.total is very low compared to published messages

### ISSUE THREAD

**Issue by anandxp** [erlio/vmq_mzbench#18]
Hi @ioolkos , 
Please consider this as a clarification rather than an issue. I really wonder whether this is a bug in our vernemq broker or i need to make any changes in my scenario , which is given below.

mqtt.message.consumed.total is 2278 whereas i published 30000 messages in mqtt.message.published.total

`make_install(git = "https://github.com/erlio/vmq_mzbench.git",
             branch = "master")

defaults("pool_size" = 100)

pool(size = 1,
     worker_type = mqtt_worker,
     worker_start = linear(100 rps)):

            connect([t(host, "dev.broker.nucleus.cantiz.com"),
                    t(port,1883),
                    t(client,"MQTT-Dev"),
                    t(clean_session,true),
                    t(keepalive_interval,60),
                    t(proto_version,4), t(reconnect_timeout,4)
                    ])

            wait(1 sec)
            subscribe("nucleus-event-topic-dev/#", 1)
            
pool(size = numvar("pool_size"),
     worker_type = mqtt_worker, 
     worker_start = linear(100 rps)):

            connect([t(host, "dev.broker.nucleus.cantiz.com"),
                    t(port,1883),
                    t(client,fixed_client_id("pool1", worker_id())),
                    t(clean_session,true),
                    t(keepalive_interval,60),
                    t(proto_version,4), t(reconnect_timeout,4)
                    ])

            set_signal(connect1, 1)
            wait_signal(connect1, 100)
            wait(4 sec)
            loop(time = 5 min, rate = 1 rps):
                publish_to_self("nucleus-event-topic-dev/", random_string(200), 1)
            disconnect()`

Also i am confused about term mqtt.publisher.qos1.puback.in.total which is 29837
Didnt get detail about above value from https://satori-com.github.io/mzbench/dashboard/ as well

![image](https://user-images.githubusercontent.com/21304150/36958891-fbb55620-2064-11e8-9ea4-307793b7f73a.png)

**Comment by anandxp** [comment]
I increased the number of pools in subsciber to 10 , still i am getting similar results.

**Comment by ioolkos** [comment]
@anandxp thanks... I did a quick run with your scenario (on my Laptop only). It worked. 

![results30](https://user-images.githubusercontent.com/282359/36964052-b5082e14-2055-11e8-8166-bdc16bcc721f.png)

Can you restart the MZBench server and retry?

To clear up the `mqtt.publisher.qos1.puback.in.total` metric: all metrics are named from the perspective of the Load testing framework. So this means that your client received ('in') this number of QoS 1 Publish Acks.

**Comment by ioolkos** [comment]
@anandxp is this issue resolved for you? have you been able to run load tests with mzbench?

**Comment by anandxp** [comment]
Hai @ioolkos !!
Missed to update here then 
I am able to publish all messages , but unable to subscribe everything

Is there any network speed pre-requisite for running the same , inorder to verify that there is no data loss and subscriber is able to subscribe everything that's published.

**Comment by anandxp** [comment]
@ioolkos 
Closing this issue as
