### ISSUE TITLE
Not able to start MZBENCH server

### ISSUE THREAD

**Issue by shariqMohammed92** [erlio/vmq_mzbench#23]
While starting the MZBENCH server I'm getting error on missing of erl_terms,docopt and requires libraries..But these libraries are already installed.
Im working on Mac OS and my pip version is PIP 9.0.1

![screen shot 2018-03-14 at 7 30 38 pm](https://user-images.githubusercontent.com/37373409/37406865-353aeb20-27be-11e8-9156-ebe6cd26a00c.png)

**Comment by ioolkos** [comment]
@shariqMohammed92 thanks... I take it that you followed the instructions from MZBench on how to install from source. I'm not sure how I can help here. Did you run the `pip install` command? Did you try running this in a python ENV?

**Comment by ioolkos** [comment]
@shariqMohammed92 have you been able to resolve this? could it be something Mac OS related?

**Comment by keerthana07** [comment]
@shariqMohammed92 were you able to resolve this issue? If so how?
I am using a mac and see the same
