### ISSUE TITLE
Could not compile on OSX

### ISSUE THREAD

**Issue by zhoub** [erlio/vmq_mzbench#29]
Hi

I tried to use this on OSX with Erlang 21.2 from BREW, and compiler reports the following error.

Thanks.

**Comment by larshesel** [comment]
Hi, I think you forgot to attach the error ;)

I don't know if I can help anyway, but I did hear someone else having issues with Erlang 21.2 from brew and I think they had better luck with Erlang 20. I'm not on mac so can't really test or verify - but thought I'd mention it anyway.
