### ISSUE TITLE
Latency units

### ISSUE THREAD

**Issue by gdhgdhgdh** [erlio/vmq_mzbench#9]
Hi, after running a few tests I'm now getting some interesting graphs. One little question comes to mind - what is the unit of latency? Is it milliseconds, microseconds, or something else?

I can't find the unit specified anywhere...

**Comment by ioolkos** [comment]
microseconds ;)

**Comment by gdhgdhgdh** [comment]
I am extremely relieved to hear this :) Three extra zeroes makes a heck of a difference...
